<a href="https://colab.research.google.com/github/UrviSoni/iNeuron.ai/blob/master/Numpy_in_details.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array

In [1]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [2]:
l = [4,5,6,7]
type(l)

list

In [3]:
np.array(l)

array([4, 5, 6, 7])

In [4]:
type(np.array(l))

numpy.ndarray

In [5]:
np.array([3,4,5,6,"adbhsf",6.4,True]) #U21 is variance of a string

array(['3', '4', '5', '6', 'adbhsf', '6.4', 'True'], dtype='<U21')

In [ ]:
#Upcasting:

In [6]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [10]:
n = np.array([1, 2, 3.0])
n.shape

(3,)

In [12]:
n.ndim

1

In [ ]:
#two dimensions

In [13]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
#Minimum dimensions 2:

In [14]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [ ]:
#dtype

In [15]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#Data-type consisting of more than one element:

In [28]:
np.array([3,4,5,6])

array([3, 4, 5, 6])

In [29]:
np.array([3,4,5,6])[0]

3

In [31]:
type(np.array([3,4,5,6])[0])

numpy.int64

In [33]:
type(np.array([3,4,5,6],dtype=np.int8))

numpy.ndarray

In [35]:
type(np.array([3,4,5,6],dtype=np.int8)[0])

numpy.int8

In [36]:
type(np.array([3,4,5,6],dtype=np.float64)[0])

numpy.float64

In [16]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')]) # Tuples are immutable datatype 
x # i2 is for 16 bit i4 is for 32 bit i8 is for 64 bit

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [17]:
x[0]

(1, 2)

In [18]:
x[0][0]

1

In [19]:
type(x[0][0])

numpy.int16

In [20]:
x[0][1]

2

In [21]:
type(x[0][1])

numpy.int64

In [22]:
x[1][0]

3

In [23]:
type(x[1][0])

numpy.int16

In [24]:
x[1][1]

4

In [25]:
type(x[1][1])

numpy.int64

In [26]:
type(x[1][0])

numpy.int16

In [ ]:

#Creating an array from sub-classes:

In [37]:
np.array([[1, 2],[4,7]])

array([[1, 2],
       [4, 7]])

In [38]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [39]:
type(np.mat(np.array([[1, 2],[4,7]]))) # matrix is a data type representation. you can convert any array into matrix. also you can covert matrix into array.

numpy.matrix

In [41]:
m = np.mat(np.array([[1, 2],[4,7]]))
type(m)

numpy.matrix

In [42]:
np.array(m)

array([[1, 2],
       [4, 7]])

In [45]:
m[0,1]

2

In [46]:
m[1,1]

7

In [43]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [44]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [ ]:
#Convert the input to an array.

In [ ]:
#Convert a list into an array:

In [47]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [48]:
type(np.asarray([1,2,3,4,5]))

numpy.ndarray

In [50]:
np.asanyarray([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [51]:
type(np.asanyarray([3,4,5,6,7]))

numpy.ndarray

In [53]:
m = np.mat([1,2,3,4,5])
m

matrix([[1, 2, 3, 4, 5]])

In [54]:
np.asanyarray(m) # matrix is a subclass of array. 

matrix([[1, 2, 3, 4, 5]])

In [55]:
np.asanyarray([1,2,3,4,5]) # if my data is available in some form of array then it will not convert it into array. if data is not available in array form then it will convert.

array([1, 2, 3, 4, 5])

In [ ]:
 a = [1, 2]
type(a)

list

In [ ]:
type(np.asarray(a))

numpy.ndarray

In [ ]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [ ]:
np.asarray((1,2))

array([1, 2])

In [ ]:
#If dtype is set, array is copied only if dtype does not match:

In [ ]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [57]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [58]:
b = a # opration is called "solocopy"
b

array([1, 2, 3, 4, 5])

In [59]:
b[0]

1

In [60]:
b[0] = 234
b

array([234,   2,   3,   4,   5])

In [61]:
a

array([234,   2,   3,   4,   5])

In [62]:
c = np.array(a,copy=True) # opration is called as "deep copy"
c

array([234,   2,   3,   4,   5])

In [63]:
c[0]

234

In [64]:
a[0]

234

In [65]:
c[0] = 454

In [66]:
a[0]

234

In [67]:
c

array([454,   2,   3,   4,   5])

In [68]:
a

array([234,   2,   3,   4,   5])

In [69]:
a[0] = 45456

In [70]:
a

array([45456,     2,     3,     4,     5])

In [71]:
c

array([454,   2,   3,   4,   5])

In [73]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [74]:
c = np.array(a)

In [75]:
c[0]

1

In [76]:
c[0] = 234

In [77]:
c

array([234,   2,   3,   4,   5])

In [78]:
a

array([1, 2, 3, 4, 5])

In [79]:
id(c)

140190037184144

In [80]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [81]:
np.array([[1,2],[3,4],[4,5,6]])

array([list([1, 2]), list([3, 4]), list([4, 5, 6])], dtype=object)

In [83]:
np.asarray([1,2,3,4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [84]:
np.asarray([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [85]:
np.asarray([1,2,3,4], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [87]:
np.asanyarray(np.mat([1,2,3,4,5]))

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.asarray([1,2]) is a

False

In [ ]:
np.asarray([1,2])

array([1, 2])

In [ ]:
np.asarray(a, dtype=np.float64) is a

False

In [ ]:
# ndarray subclasses are not passed through

In [ ]:
issubclass(np.matrix, np.ndarray)

True

In [ ]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [ ]:
np.asarray(a) is a

False

In [ ]:
np.asanyarray(a) is a

True

In [ ]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [ ]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [ ]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [ ]:
np.asanyarray([1,2]) is a

True

#numpy.copy

In [ ]:
np.array(a, copy=True)  

array([[1, 2]])

In [ ]:
#Create an array x, with a reference y and a copy z:

In [ ]:
x = np.array([1, 2, 3])
x
y

array([1, 2, 3])

In [ ]:
y = x

In [ ]:
z = np.copy(x)

In [ ]:
y[0] = 100
x

array([100,   2,   3])

In [ ]:
x

array([100,   2,   3])

In [ ]:
id(x[0])

4767545360

In [ ]:
id(y[0])

4767545408

In [ ]:
id(x) 

4768156128

In [ ]:
id(y)

4768156128

# numpy.fromfunction

In [ ]:
#Construct an array by executing a function over each coordinate.

In [99]:
def test(a,b,c):
  return a*b*c

In [102]:
np.fromfunction(test,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [88]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [89]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [91]:
np.fromfunction(lambda i, j, k: i * j * k, (3, 3, 3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [93]:
np.fromfunction(lambda i, j, k: i * j * k, (3, 3, 2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [94]:
np.fromfunction(lambda i, j, k, m: i * j * k * m, (3, 3, 2, 2), dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]]])

In [95]:
a  = np.fromfunction(lambda i, j, k: i * j * k, (3, 3, 2), dtype=int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [96]:
a[2]

array([[0, 0],
       [0, 2],
       [0, 4]])

In [97]:
a[2][2]

array([0, 4])

In [98]:
a[2][2][1]

4

In [90]:
np.fromfunction(lambda i, j: i / j, (3, 3), dtype=int)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [103]:
l = [1,2,3,4,5,6,7,8]
for i in l:
  print(i)

1
2
3
4
5
6
7
8


In [104]:
for x in range(5):
  print(x)

0
1
2
3
4


In [105]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x7f8089607570>

In [106]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#A new 1-D array initialized from text data in a string

In [107]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [ ]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [ ]:
# How to create create a record array from a (flat) list of arrays

In [108]:
x1=np.array([1,2,3,4])

In [109]:
x2=np.array(['a','dd','xyz','12'])

In [110]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [111]:
r = np.core.records.fromarrays([x1,x2,x3,x4]) # i4 = integer, U3 = string, f8 = float
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('f0', '<i8'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<f8')])

In [ ]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [112]:
r[1]

(2, 'dd', 2., 2.)

In [113]:
r[1][1]

'dd'

In [ ]:
print(r[1]["a"])

2


x1[1]=34

In [ ]:
x1[1]

2

# data types

In [114]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [116]:
l = np.array([2,3,4,5,6])
a = np.array(l)

In [117]:
b = np.array([[3,4,5],[6,7,8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [118]:
a.ndim

1

In [119]:
b.ndim

2

In [120]:
a.size

5

In [121]:
b.size

6

In [122]:
a.shape

(5,)

In [123]:
b.shape # row = 2, column = 3

(2, 3)

In [124]:
a.dtype

dtype('int64')

In [125]:
b.dtype

dtype('int64')

In [126]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [127]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [128]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [129]:
range(5)

range(0, 5)

In [130]:
list(range(5))

[0, 1, 2, 3, 4]

In [131]:
list(range(1,5))

[1, 2, 3, 4]

In [132]:
list(range(1,5,2)) # range is always going to take arguments as integer. It's not consider arguments as float

[1, 3]

In [133]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [134]:
np.arange(3.5,9,.2) # arange function is going to take floating arguments whereas range is only going to consider integer

array([3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5, 5.7, 5.9,
       6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5, 7.7, 7.9, 8.1, 8.3, 8.5,
       8.7, 8.9])

In [135]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [136]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [137]:
list(range(50,-1,5))

[]

In [138]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [139]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [140]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [141]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [143]:
np.linspace(1,4)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [144]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [145]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

# Matrix creation

In [146]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [147]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [148]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [149]:
np.zeros((5,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [150]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [151]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [153]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples
# 5 such matrixes with row = 2 and columns = 8


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [155]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [157]:
np.ones((3,4))+4

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [158]:
np.ones((3,4))*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [159]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
np.arange(3,7,2)

array([3, 5])

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [ ]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519])

In [ ]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [ ]:
#Extract a diagonal or construct a diagonal array.

In [ ]:
x = np.arange(16).reshape((-1,4))

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.diag(x)

array([ 0,  5, 10, 15])

In [ ]:
np.diag(x, k=2
       )

array([2, 7])

In [ ]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [ ]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [ ]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [ ]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [ ]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [ ]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [ ]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [ ]:
#return a Lower triangle of an array.

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [ ]:
#return Upper triangle of an array.

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.79234365 0.26636652 0.84876143]
 [0.78766627 0.06627396 0.8829639 ]]


In [ ]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.08550888  0.73651756  0.08329424]
 [ 0.75179279  0.42441618  0.47752353]
 [ 0.23835886  1.06582108 -0.01790105]
 [ 0.48190152 -0.24940656 -0.44992115]]


In [ ]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 4

Random integer matrix


In [ ]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[28 90 28 25]
 [14 51 32 98]
 [10 98 11 71]
 [12 42 54 77]]

20 samples drawn from a dice throw: [1 6 2 1 1 1 5 2 5 1 1 5 5 1 6 6 5 4 1 1]


# Reshaping

In [ ]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[51, 63, 51, 54, 96],
       [11, 93,  2, 51, 34],
       [62, 35, 42, 95, 58],
       [88, 44, 36, 93, 83],
       [86, 56, 30,  2, 15],
       [68, 40, 77, 48, 57]])

In [ ]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [72 69 61 67 42  2 92 42 38 56 22 71 21 81 81 47  2  1  6 94 52 14 87 71
 38 57 99 87 62 88] 
 --------------------

b looks like
 -------------------- 
 [[[72 69 61 67 42]
  [ 2 92 42 38 56]
  [22 71 21 81 81]]

 [[47  2  1  6 94]
  [52 14 87 71 38]
  [57 99 87 62 88]]] 
 --------------------

c looks like
 -------------------- 
 [[72 69 61 67 42]
 [ 2 92 42 38 56]
 [22 71 21 81 81]
 [47  2  1  6 94]
 [52 14 87 71 38]
 [57 99 87 62 88]] 
 --------------------


In [ ]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [69 99 45 72 41 16 50 80 80 22]

Here is the sorted vector
 -------------------------------------------------- 
 [16 22 41 45 50 69 72 80 80 99]


In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[18 25 38 73 94]
 [18 42 75 79 91]
 [21 44 62 78 85]
 [15 17 44 89 91]
 [ 3 24 38 62 86]]


array([[18, 94, 25, 38, 73],
       [75, 42, 79, 18, 91],
       [21, 44, 85, 78, 62],
       [91, 15, 17, 44, 89],
       [62, 38,  3, 24, 86]])

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 99
Max of b: 96


array([[[51, 63, 51, 54, 96],
        [11, 93,  2, 51, 34],
        [62, 35, 42, 95, 58]],

       [[88, 44, 36, 93, 83],
        [86, 56, 30,  2, 15],
        [68, 40, 77, 48, 57]]])

In [ ]:
M

array([[46, 88, 23, 66, 57],
       [50, 90, 30, 46, 36],
       [31, 19, 42, 23, 31],
       [ 4, 44, 86, 10, 81],
       [73, 35, 30, 99, 43]])

In [ ]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [1 1 2 2 3]
Max of b location: 4
Max of c location: 4


# Indexing and slicing

In [ ]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [ ]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [ ]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[35 75 44 59 85]
 [71 58 75 72 69]
 [76 97 49 63 53]]


array([[75, 59],
       [58, 72],
       [97, 63]])

In [ ]:
mat[0:3,[1,3]]
mat

array([[35, 75, 44, 59, 85],
       [71, 58, 75, 72, 69],
       [76, 97, 49, 63, 53]])

In [ ]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 58


array([[35, 75, 44, 59, 85],
       [71, 58, 75, 72, 69],
       [76, 97, 49, 63, 53]])

In [ ]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 75

Row or column extract
----------------------


In [ ]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [22 10 57 59 61]
Entire column at index 3: [92 88 59]


In [ ]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[14 32]
 [62 27]]


In [ ]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[77 69]
 [64 17]]


# Subseting

In [ ]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[51 99 67 32 43]
 [53 61 80 97 51]
 [82 76 18 26 11]]


array([[ True,  True,  True, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False]])

In [ ]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [51 99 67 53 61 80 97 51 82 76]


# Slicing

In [ ]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [ ]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [ ]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [ ]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [ ]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 3 9]
 [6 1 8]
 [5 9 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 5 7]
 [4 4 9]
 [1 2 5]]


In [ ]:
mat1*mat2

array([[ 9, 15, 63],
       [24,  4, 72],
       [ 5, 18,  5]])

In [ ]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 30  45  93]
 [ 30  50  91]
 [ 52  63 121]]


In [ ]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/Users/sudhanshukumar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[103 103 109]
 [106 101 108]
 [105 109 101]]


In [ ]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27  27 729]
 [216   1 512]
 [125 729   1]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27  27 729]
 [216   1 512]
 [125 729   1]]


# Broadcasting

In [ ]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [ ]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 5 4]
 [1 7 3]
 [8 3 5]]

2nd Matrix of random single-digit numbers
------------
 [[4 8 6]
 [7 6 8]
 [4 6 5]]


In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[3.         2.23606798 2.        ]
 [1.         2.64575131 1.73205081]
 [2.82842712 1.73205081 2.23606798]]


In [ ]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 1.48413159e+02 5.45981500e+01]
 [2.71828183e+00 1.09663316e+03 2.00855369e+01]
 [2.98095799e+03 2.00855369e+01 1.48413159e+02]]


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.69897    0.60205999]
 [0.         0.84509804 0.47712125]
 [0.90308999 0.47712125 0.69897   ]]
[[9 5 4]
 [1 7 3]
 [8 3 5]]
[[4 8 6]
 [7 6 8]
 [4 6 5]]


In [ ]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 5 4]
 [1 1 3]
 [0 3 0]]


array([[1, 5, 4],
       [1, 1, 3],
       [0, 3, 0]])

In [ ]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [ ]:
A = np.linspace(0,12*np.pi,1001)


In [ ]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])