<a href="https://colab.research.google.com/github/UrviSoni/iNeuron.ai/blob/master/Numpy_in_details.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array

In [8]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [ ]:
l = [4,5,6,7]
type(l)

list

In [ ]:
np.array(l)

array([4, 5, 6, 7])

In [ ]:
type(np.array(l))

numpy.ndarray

In [ ]:
np.array([3,4,5,6,"adbhsf",6.4,True]) #U21 is variance of a string

array(['3', '4', '5', '6', 'adbhsf', '6.4', 'True'], dtype='<U21')

In [ ]:
#Upcasting:

In [ ]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [ ]:
n = np.array([1, 2, 3.0])
n.shape

(3,)

In [ ]:
n.ndim

1

In [ ]:
#two dimensions

In [ ]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
#Minimum dimensions 2:

In [ ]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [ ]:
#dtype

In [ ]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#Data-type consisting of more than one element:

In [ ]:
np.array([3,4,5,6])

array([3, 4, 5, 6])

In [ ]:
np.array([3,4,5,6])[0]

3

In [ ]:
type(np.array([3,4,5,6])[0])

numpy.int64

In [ ]:
type(np.array([3,4,5,6],dtype=np.int8))

numpy.ndarray

In [ ]:
type(np.array([3,4,5,6],dtype=np.int8)[0])

numpy.int8

In [ ]:
type(np.array([3,4,5,6],dtype=np.float64)[0])

numpy.float64

In [ ]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')]) # Tuples are immutable datatype 
x # i2 is for 16 bit i4 is for 32 bit i8 is for 64 bit

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [ ]:
x[0]

(1, 2)

In [ ]:
x[0][0]

1

In [ ]:
type(x[0][0])

numpy.int16

In [ ]:
x[0][1]

2

In [ ]:
type(x[0][1])

numpy.int64

In [ ]:
x[1][0]

3

In [ ]:
type(x[1][0])

numpy.int16

In [ ]:
x[1][1]

4

In [ ]:
type(x[1][1])

numpy.int64

In [ ]:
type(x[1][0])

numpy.int16

In [ ]:

#Creating an array from sub-classes:

In [ ]:
np.array([[1, 2],[4,7]])

array([[1, 2],
       [4, 7]])

In [ ]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [ ]:
type(np.mat(np.array([[1, 2],[4,7]]))) # matrix is a data type representation. you can convert any array into matrix. also you can covert matrix into array.

numpy.matrix

In [ ]:
m = np.mat(np.array([[1, 2],[4,7]]))
type(m)

numpy.matrix

In [ ]:
np.array(m)

array([[1, 2],
       [4, 7]])

In [ ]:
m[0,1]

2

In [ ]:
m[1,1]

7

In [ ]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [ ]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [ ]:
#Convert the input to an array.

In [ ]:
#Convert a list into an array:

In [ ]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
type(np.asarray([1,2,3,4,5]))

numpy.ndarray

In [ ]:
np.asanyarray([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [ ]:
type(np.asanyarray([3,4,5,6,7]))

numpy.ndarray

In [ ]:
m = np.mat([1,2,3,4,5])
m

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.asanyarray(m) # matrix is a subclass of array. 

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.asanyarray([1,2,3,4,5]) # if my data is available in some form of array then it will not convert it into array. if data is not available in array form then it will convert.

array([1, 2, 3, 4, 5])

In [ ]:
 a = [1, 2]
type(a)

list

In [ ]:
type(np.asarray(a))

numpy.ndarray

In [ ]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [ ]:
np.asarray((1,2))

array([1, 2])

In [ ]:
#If dtype is set, array is copied only if dtype does not match:

In [ ]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
b = a # opration is called "solocopy"
b

array([1, 2, 3, 4, 5])

In [ ]:
b[0]

1

In [ ]:
b[0] = 234
b

array([234,   2,   3,   4,   5])

In [ ]:
a

array([234,   2,   3,   4,   5])

In [ ]:
c = np.array(a,copy=True) # opration is called as "deep copy"
c

array([234,   2,   3,   4,   5])

In [ ]:
c[0]

234

In [ ]:
a[0]

234

In [ ]:
c[0] = 454

In [ ]:
a[0]

234

In [ ]:
c

array([454,   2,   3,   4,   5])

In [ ]:
a

array([234,   2,   3,   4,   5])

In [ ]:
a[0] = 45456

In [ ]:
a

array([45456,     2,     3,     4,     5])

In [ ]:
c

array([454,   2,   3,   4,   5])

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
c = np.array(a)

In [ ]:
c[0]

1

In [ ]:
c[0] = 234

In [ ]:
c

array([234,   2,   3,   4,   5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
id(c)

140190037184144

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([[1,2],[3,4],[4,5,6]])

array([list([1, 2]), list([3, 4]), list([4, 5, 6])], dtype=object)

In [ ]:
np.asarray([1,2,3,4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [ ]:
np.asarray([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [ ]:
np.asarray([1,2,3,4], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
np.asanyarray(np.mat([1,2,3,4,5]))

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.asarray([1,2]) is a

False

In [ ]:
np.asarray([1,2])

array([1, 2])

In [ ]:
np.asarray(a, dtype=np.float64) is a

False

In [ ]:
# ndarray subclasses are not passed through

In [ ]:
issubclass(np.matrix, np.ndarray)

True

In [ ]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [ ]:
np.asarray(a) is a

False

In [ ]:
np.asanyarray(a) is a

True

In [ ]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [ ]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [ ]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [ ]:
np.asanyarray([1,2]) is a

True

#numpy.copy

In [ ]:
np.array(a, copy=True)  

array([[1, 2]])

In [ ]:
#Create an array x, with a reference y and a copy z:

In [ ]:
x = np.array([1, 2, 3])
x
y

array([1, 2, 3])

In [ ]:
y = x

In [ ]:
z = np.copy(x)

In [ ]:
y[0] = 100
x

array([100,   2,   3])

In [ ]:
x

array([100,   2,   3])

In [ ]:
id(x[0])

4767545360

In [ ]:
id(y[0])

4767545408

In [ ]:
id(x) 

4768156128

In [ ]:
id(y)

4768156128

# numpy.fromfunction

In [ ]:
#Construct an array by executing a function over each coordinate.

In [ ]:
def test(a,b,c):
  return a*b*c

In [ ]:
np.fromfunction(test,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [ ]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [ ]:
np.fromfunction(lambda i, j, k: i * j * k, (3, 3, 3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [ ]:
np.fromfunction(lambda i, j, k: i * j * k, (3, 3, 2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [ ]:
np.fromfunction(lambda i, j, k, m: i * j * k * m, (3, 3, 2, 2), dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]]])

In [ ]:
a  = np.fromfunction(lambda i, j, k: i * j * k, (3, 3, 2), dtype=int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [ ]:
a[2]

array([[0, 0],
       [0, 2],
       [0, 4]])

In [ ]:
a[2][2]

array([0, 4])

In [ ]:
a[2][2][1]

4

In [ ]:
np.fromfunction(lambda i, j: i / j, (3, 3), dtype=int)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [ ]:
l = [1,2,3,4,5,6,7,8]
for i in l:
  print(i)

1
2
3
4
5
6
7
8


In [ ]:
for x in range(5):
  print(x)

0
1
2
3
4


In [ ]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x7f8089607570>

In [ ]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#A new 1-D array initialized from text data in a string

In [ ]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [ ]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [ ]:
# How to create create a record array from a (flat) list of arrays

In [ ]:
x1=np.array([1,2,3,4])

In [ ]:
x2=np.array(['a','dd','xyz','12'])

In [ ]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [ ]:
r = np.core.records.fromarrays([x1,x2,x3,x4]) # i4 = integer, U3 = string, f8 = float
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('f0', '<i8'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<f8')])

In [ ]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [ ]:
r[1]

(2, 'dd', 2., 2.)

In [ ]:
r[1][1]

'dd'

In [ ]:
print(r[1]["a"])

2


x1[1]=34

In [ ]:
x1[1]

2

# data types

In [ ]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [ ]:
l = np.array([2,3,4,5,6])
a = np.array(l)

In [ ]:
b = np.array([[3,4,5],[6,7,8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.size

5

In [ ]:
b.size

6

In [ ]:
a.shape

(5,)

In [ ]:
b.shape # row = 2, column = 3

(2, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [ ]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [1]:
range(5)

range(0, 5)

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(1,5))

[1, 2, 3, 4]

In [4]:
list(range(1,5,2)) # range is always going to take arguments as integer. It's not consider arguments as float

[1, 3]

In [5]:
np.arange(3,9)

NameError: ignored

In [ ]:
np.arange(3.5,9,.2) # arange function is going to take floating arguments whereas range is only going to consider integer

In [ ]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

In [ ]:
list(range(5,16,2))

In [ ]:
list(range(50,-1,5))

In [ ]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

In [ ]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

In [ ]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

In [ ]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

In [ ]:
np.linspace(1,4)

In [ ]:
np.linspace(1,100,10)

In [ ]:
np.linspace(1,100,100)

# Matrix creation

In [ ]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((5,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [ ]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples
# 5 such matrixes with row = 2 and columns = 8


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((3,4))+4

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.ones((3,4))*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
np.arange(3,7,2)

array([3, 5])

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [ ]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519])

In [ ]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [ ]:
#Extract a diagonal or construct a diagonal array.

In [9]:
x = np.arange(16).reshape((-1,4))

In [10]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.diag(x)

array([ 0,  5, 10, 15])

In [12]:
np.diag(x, k=0)

array([ 0,  5, 10, 15])

In [13]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [ ]:
np.diag(x, k=2)

array([2, 7])

In [14]:
np.diag(x, k=3)

array([3])

In [17]:
x = np.arange(18).reshape((3,6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [18]:
np.diag(x)

array([ 0,  7, 14])

In [19]:
np.diag(x, k=0)

array([ 0,  7, 14])

In [20]:
np.diag(x, k=1)

array([ 1,  8, 15])

In [21]:
np.diag(x, k=2)

array([ 2,  9, 16])

In [22]:
np.diag(x, k=3)

array([ 3, 10, 17])

In [23]:
np.diag(x, k=4)

array([ 4, 11])

In [24]:
np.diag(x, k=5)

array([5])

In [25]:
np.diag(x, k=6)

array([], dtype=int64)

In [26]:
np.diag(x, k=-1)

array([ 6, 13])

In [27]:
np.diag(x, k=-2)

array([12])

In [28]:
np.diag(x, k=-3)

array([], dtype=int64)

In [ ]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [29]:
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
np.diag(x)

array([ 0,  5, 10, 15])

In [31]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [32]:
np.diag(x, k=-2)

array([ 8, 13])

In [33]:
np.diag(x, k=-3)

array([12])

In [34]:
np.diag(x, k=-4)

array([], dtype=int64)

In [35]:
np.diag(x)

array([ 0,  5, 10, 15])

In [36]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [ ]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [37]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [38]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [ ]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [39]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [40]:
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [41]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [42]:
np.tri(3, 5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [ ]:
#return a Lower triangle of an array.

In [43]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [44]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], -1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [ ]:
#return Upper triangle of an array.

In [45]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [46]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.85855885 0.07281595 0.37580205]
 [0.64012286 0.95093706 0.04199047]]


In [48]:
np.random.rand(2,3)

array([[0.77822256, 0.93254832, 0.24679402],
       [0.20348695, 0.93668319, 0.52897973]])

In [49]:
np.random.rand(2,3,4)

array([[[0.05241469, 0.92357042, 0.40336224, 0.48502247],
        [0.77372737, 0.77526023, 0.22089466, 0.84678284],
        [0.79392696, 0.10695784, 0.27807731, 0.02707697]],

       [[0.05397959, 0.46714651, 0.72949953, 0.87851509],
        [0.83365754, 0.13031261, 0.94060264, 0.91816323],
        [0.1101036 , 0.78396615, 0.09177421, 0.21373318]]])

In [50]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.64675392  2.11944194 -0.31888689]
 [ 0.5028487  -0.80374069 -1.28466934]
 [ 0.20074546 -1.12299207 -0.77622139]
 [-0.12011947 -0.01567753 -1.47534293]]


In [51]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 2

Random integer matrix


In [52]:
np.random.randint(1,10)

2

In [53]:
np.random.randint(1,10,(4,5,2))

array([[[2, 3],
        [5, 3],
        [5, 5],
        [5, 3],
        [4, 1]],

       [[7, 4],
        [5, 6],
        [1, 8],
        [2, 1],
        [6, 5]],

       [[9, 4],
        [5, 9],
        [9, 2],
        [1, 6],
        [5, 1]],

       [[7, 2],
        [4, 2],
        [4, 6],
        [1, 8],
        [4, 7]]])

In [54]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[84 88  7 61]
 [22 45 56 36]
 [12 73 67  7]
 [36 25 95 92]]

20 samples drawn from a dice throw: [5 2 4 3 1 6 4 5 4 2 1 6 1 6 5 4 2 5 6 4]


# Reshaping

In [55]:
from numpy.random import randint as ri

In [56]:
ri(1,100,30)

array([69, 62,  7, 51, 95, 67,  4, 53, 21, 85, 32, 17, 90, 49, 85, 92, 16,
       33, 23,  8, 47, 76,  6, 37, 77, 54, 71, 53, 35, 88])

In [57]:
ri(1,100,30).reshape(5,3,2)

array([[[94, 46],
        [22, 42],
        [17, 71]],

       [[43, 71],
        [49,  2],
        [51, 49]],

       [[ 7, 92],
        [52, 77],
        [ 5, 50]],

       [[ 8, 27],
        [44, 71],
        [53,  8]],

       [[81, 34],
        [66, 46],
        [45, 43]]])

In [58]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[59, 87, 45, 42, 46],
       [49, 55, 11, 13, 82],
       [46, 83, 28, 20, 14],
       [ 4, 52, 57, 28, 44],
       [36, 33, 13, 69, 59],
       [16, 55, 29, 64, 46]])

In [60]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [61]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [59 87 45 42 46 49 55 11 13 82 46 83 28 20 14  4 52 57 28 44 36 33 13 69
 59 16 55 29 64 46] 
 --------------------

b looks like
 -------------------- 
 [[[59 87 45 42 46]
  [49 55 11 13 82]
  [46 83 28 20 14]]

 [[ 4 52 57 28 44]
  [36 33 13 69 59]
  [16 55 29 64 46]]] 
 --------------------

c looks like
 -------------------- 
 [[59 87 45 42 46]
 [49 55 11 13 82]
 [46 83 28 20 14]
 [ 4 52 57 28 44]
 [36 33 13 69 59]
 [16 55 29 64 46]] 
 --------------------


In [62]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [93 74 30 30 91  5 29 72 55 21]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 21 29 30 30 55 72 74 91 93]


In [63]:
M = ri(1,100,25).reshape(5,5)
M

array([[50, 50,  5, 83, 47],
       [ 2, 81, 48, 48, 45],
       [ 7, 24, 59, 35, 13],
       [92, 35, 86, 40, 99],
       [94, 62, 18, 92,  1]])

In [64]:
np.sort(M, axis=1, kind="mergesort")

array([[ 5, 47, 50, 50, 83],
       [ 2, 45, 48, 48, 81],
       [ 7, 13, 24, 35, 59],
       [35, 40, 86, 92, 99],
       [ 1, 18, 62, 92, 94]])

In [65]:
np.sort(M, axis=0, kind="mergesort") # row wise sorting

array([[ 2, 24,  5, 35,  1],
       [ 7, 35, 18, 40, 13],
       [50, 50, 48, 48, 45],
       [92, 62, 59, 83, 47],
       [94, 81, 86, 92, 99]])

In [66]:
np.sort(M) # column wise sorting 

array([[ 5, 47, 50, 50, 83],
       [ 2, 45, 48, 48, 81],
       [ 7, 13, 24, 35, 59],
       [35, 40, 86, 92, 99],
       [ 1, 18, 62, 92, 94]])

In [67]:
M

array([[50, 50,  5, 83, 47],
       [ 2, 81, 48, 48, 45],
       [ 7, 24, 59, 35, 13],
       [92, 35, 86, 40, 99],
       [94, 62, 18, 92,  1]])

In [69]:
M.max()

99

In [70]:
M.argmax(axis = 1)

array([3, 1, 2, 4, 0])

In [71]:
M.argmax(axis = 0)

array([4, 1, 3, 4, 3])

In [72]:
M.argmax()

19

In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[18 25 38 73 94]
 [18 42 75 79 91]
 [21 44 62 78 85]
 [15 17 44 89 91]
 [ 3 24 38 62 86]]


array([[18, 94, 25, 38, 73],
       [75, 42, 79, 18, 91],
       [21, 44, 85, 78, 62],
       [91, 15, 17, 44, 89],
       [62, 38,  3, 24, 86]])

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 99
Max of b: 96


array([[[51, 63, 51, 54, 96],
        [11, 93,  2, 51, 34],
        [62, 35, 42, 95, 58]],

       [[88, 44, 36, 93, 83],
        [86, 56, 30,  2, 15],
        [68, 40, 77, 48, 57]]])

In [ ]:
M

array([[46, 88, 23, 66, 57],
       [50, 90, 30, 46, 36],
       [31, 19, 42, 23, 31],
       [ 4, 44, 86, 10, 81],
       [73, 35, 30, 99, 43]])

In [ ]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [1 1 2 2 3]
Max of b location: 4
Max of c location: 4


# Indexing and slicing

In [73]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [74]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [75]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [76]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [78]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [79]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [80]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [81]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[24, 47, 66, 49, 11],
       [51, 23, 76, 77, 49],
       [19, 18, 64, 99, 85]])

In [83]:
mat[1:,2:]

array([[76, 77, 49],
       [64, 99, 85]])

In [84]:
mat[[1,2],2:]

array([[76, 77, 49],
       [64, 99, 85]])

In [85]:
mat[1:3,2:5]

array([[76, 77, 49],
       [64, 99, 85]])

In [86]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[36 74 75 60 92]
 [99 83 97 41 53]
 [71 34 97 33 49]]


array([[74, 60],
       [83, 41],
       [34, 33]])

In [87]:
mat[0:3,[1,3]]
mat

array([[36, 74, 75, 60, 92],
       [99, 83, 97, 41, 53],
       [71, 34, 97, 33, 49]])

In [88]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 83


array([[36, 74, 75, 60, 92],
       [99, 83, 97, 41, 53],
       [71, 34, 97, 33, 49]])

In [89]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 97

Row or column extract
----------------------


In [90]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [71 34 97 33 49]
Entire column at index 3: [60 41 33]


In [91]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[41 53]
 [33 49]]


In [92]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[74 60]
 [83 41]]


# Subseting

In [93]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[34, 73, 75, 24, 26],
       [28, 25, 24, 33, 27],
       [13, 26, 43, 41, 49]])

In [94]:
mat>30

array([[ True,  True,  True, False, False],
       [False, False, False,  True, False],
       [False, False,  True,  True,  True]])

In [95]:
mat[mat>30]

array([34, 73, 75, 33, 43, 41, 49])

In [96]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[58 43 72 45 17]
 [63 78 66 89 36]
 [48 56 59 46 83]]


array([[ True, False,  True, False, False],
       [ True,  True,  True,  True, False],
       [False,  True,  True, False,  True]])

In [97]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [58 72 63 78 66 89 56 59 83]


# Slicing

In [98]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [99]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [ ]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [ ]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [ ]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [ ]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [100]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[9 4 5]
 [4 6 1]
 [5 1 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 2 6]
 [9 7 6]
 [8 4 4]]


In [101]:
mat1*mat2

array([[27,  8, 30],
       [36, 42,  6],
       [40,  4, 32]])

In [102]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2) # here, @ is used for 'mmatrix multiplication 



Multiplication
------------------
 [[103  66  98]
 [ 74  54  64]
 [ 88  49  68]]


In [103]:
9/0

ZeroDivisionError: ignored

In [104]:
mat1

array([[9, 4, 5],
       [4, 6, 1],
       [5, 1, 8]])

In [105]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [106]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[109 104 105]
 [104 106 101]
 [105 101 108]]


In [107]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[729  64 125]
 [ 64 216   1]
 [125   1 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[729  64 125]
 [ 64 216   1]
 [125   1 512]]


# Broadcasting

In [ ]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [108]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
np.zeros((4,4)) + 100

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [110]:
a = np.zeros((4,4)) + 100

In [111]:
a

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [112]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [113]:
a + add_rows

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.]])

In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [114]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [115]:
a + add_cols

array([[100., 100., 100., 100.],
       [101., 101., 101., 101.],
       [102., 102., 102., 102.],
       [103., 103., 103., 103.]])

In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [116]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[5 7 4]
 [9 5 2]
 [4 4 3]]

2nd Matrix of random single-digit numbers
------------
 [[8 3 6]
 [3 4 3]
 [7 2 6]]


In [117]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.23606798 2.64575131 2.        ]
 [3.         2.23606798 1.41421356]
 [2.         2.         1.73205081]]


In [118]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.48413159e+02 1.09663316e+03 5.45981500e+01]
 [8.10308393e+03 1.48413159e+02 7.38905610e+00]
 [5.45981500e+01 5.45981500e+01 2.00855369e+01]]


In [119]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    0.84509804 0.60205999]
 [0.95424251 0.69897    0.30103   ]
 [0.60205999 0.60205999 0.47712125]]
[[5 7 4]
 [9 5 2]
 [4 4 3]]
[[8 3 6]
 [3 4 3]
 [7 2 6]]


In [120]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[5 1 4]
 [0 1 2]
 [4 0 3]]


array([[5, 1, 4],
       [0, 1, 2],
       [4, 0, 3]])

In [ ]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [121]:
A = np.linspace(0,12*np.pi,1001)


In [122]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])

In [123]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
9**100

265613988875874769338781322035779626829233452653394495974574961739092490901302182994384699044001

In [125]:
mat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [127]:
mat[[1,2],1:]

array([[22, 23],
       [32, 33]])